version: '3.8'
services:
  db_enterprise:
    image: postgres
    container_name: db_enterprise
    restart: always
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=enterprise
    ports:
      - 5432:5432

  db_employee:
    image: postgres
    container_name: db_employee
    restart: always
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=employee
    ports:
      - 5431:5432

  api_enterprise:
    image: node
    restart: always
    container_name: api_enterprise
    command: npm run start:dev
    working_dir: /app
    volumes:
      - ./enterprise:/app
    environment:
      - API_PORT=3000
      - DB_HOST=db_enterprise
      - DB_PASS=postgres
      - DB_USER=postgres
      - DB_PORT=5432
    ports:
      - 3000:3000
    env_file:
      - ./enterprise/.env

  api_employee:
    image: node
    restart: always
    container_name: api_employee
    command: npm run start:dev
    working_dir: /app
    volumes:
      - ./employee:/app
    environment:
      - API_PORT=3001
      - DB_HOST=db_employee
      - DB_PASS=postgres
      - DB_USER=postgres
      - DB_PORT=5432
    ports:
      - 3001:3001
    env_file:
      - ./employee/.env

volumes:
  db:
    driver: local
